### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1136] opened 2024-02-05 14:45 UTC
We start to have a lot of major versions failing to update in nodeJS packages. 

Also, Jupiter Lab is now at  4.10 while we are at 3.5. 
To keep up with all the updates we need to refactor the project entirely. 

Build extensions using https://github.com/jupyterlab/extension-template

**Comment by gpelouze** [comment] 2024-06-26 13:39
Duplicate of https://github.com/QCDIS/projects_overview/issues/226

**Closed by gpelouze** 2024-06-26 13:39 UTC
Labels: Initiative
